### PR TITLE
Change table crossjoin algorytm

### PR DESCRIPTION
**Pull request by hohlick**
In my opinion, Table.ExpandTableColumn (which is actually used in referenced Table.ExpandTables function) is a very resources cvonsuming, specially when we try to make crossjoin. 
Using of Table.Join with necessary column renaming could improve performance significantly.

### CODE REVIEW

**Comment by tycho01** [comment]
Hey, thanks for this! :)

That `List.Accumulate` looks pretty cool. I don't think that'd been around when I made this, and it looks way better than the iteration I'd been doing.
I just tried updating that to use it too, which perhaps helps improve that a little bit as well.

On actual performance, it sounds like you've got more experience here than I do though.

On another note, I'd just been trying to figure out how to use this to self-join a table, which gave the extra complication of having to deal with column name clashes.

For that I was trying this:
```
(
  Tables as list,
  optional TableNames as list, // names to append as prefixes, if desired, defaults to {1, 2, 3, ...}
  optional AppendParentNames as logical    //whether to use append parent column names
) as table =>
let
  AppendParentNames = if (AppendParentNames=null) then false else AppendParentNames,
  Cols = if (TableNames=null) then TableNames else List.Transform(List.Numbers(1, List.Count(Tables)), each Number.ToText(_))
in
  ExpandTables(#table(Cols, {Tables}), null, AppendParentNames)
```

If your approach is more performant, might it perhaps be possible to incorporate something similar there so we could somehow get the best of both worlds? Otherwise perhaps I could include the clash-proof version separately or something.

**Comment by hohlick** [comment]
> On actual performance, it sounds like you've got more experience here than I do though.
don't think so :) this is a special case where I tested a lot of ways.

As far as I can see there is a special parameter `AppendParentNames` which adds a table name prefix, based on table count/number.
Actually I added this too, but only for the same column names:
`NewNames = List.Transform(OldNames, each if List.Contains(CurrentNames, _) then Text.From(current+1) & "_" & _ else _)`
and then rename columns in the table before join. As `current` is a zero-based index, my code do what you proposed as well, except it didn't adds an index to the first (leftmost) table.

Test it, I think we can make a good solution together

**Comment by tycho01** [comment]
Okay, sounds like we're just about there then!
Attempt to add customization to yours:
```
(
  tables as list,
  optional TableNames as list, // names to append as prefixes on clash or if desired, default {1, 2, 3, ...}
  optional AlwaysPrefix as logical    //whether to use append table names if without column name clashes
) as table =>
    let 
        CrossJoin = List.Accumulate(
            List.Positions(tables),
            #table({},{}), 
            (state, current) => 
                let
                    CurrentTable = tables{current}, // need check for table type?
                    CurrentNames = Table.ColumnNames(state),
                    OldNames = Table.ColumnNames(CurrentTable),
                    Prefix = if TableNames <> null then TableNames{current} else Text.From(current+1),
                    NewNames = List.Transform(OldNames, each if List.Contains(CurrentNames, _) then Prefix & "_" & _ else _),
                    Renamed = Table.RenameColumns(CurrentTable, List.Zip({OldNames, NewNames}))
                in
                    Table.Join(state, {}, Renamed, {}, JoinKind.FullOuter)
            )
    in
        if List.IsEmpty(tables) 
            then #table({},{}) 
            else CrossJoin
```

Minor bikeshed, I sorta liked `.` to bind the prefixes as that was what it seemed to use by default if you expand stuff, but yeah, whichever.

**Comment by hohlick** [comment]
I'd prefer to replace this:
```Prefix = if TableNames <> null then TableNames{current} else Text.From(current+1),```
with that:
```Prefix = if TableNames <> null then try TableNames{current} otherwise Text.From(current+1) else Text.From(current+1)```
to prevent errors when TableNames list is somewhy shorter than tables list. Just to be sure.

> I sorta liked . to bind the prefixes
Do as you like. I have no preferences there

**Comment by tycho01** [comment]
Looks good, yeah. Added that in now. :)

**Pull request closed without merging**
