### PR TITLE
New statistical function: TREND

### PR DESCRIPTION
**Pull request by ImkeF**
Hi Tycho,
I'm completely new to GitHub, so please bear with me. Actually: Do you know if there is a beginners guide for non-techies somewhere? Even the official instructions here sound chinese to me unfortunately.

I'm trying to contribute an M-function for descriptive statistics with a blogpost coming soon, hoping that many other people will create and share statistical functions for M. So I would like to link to your repository - and ideally give non-techies who can just about code M like me an easy start here :-)

### CODE REVIEW

**Comment by tycho01** [comment]
Hey,
No worries, I guess use of Github for Power Query is still pretty young in general. :)

[Here's](http://rogerdudler.github.io/git-guide/) a guide on Git itself, but ideally with Github's GUI you may even get away not bothering with those internals. Presuming you use Windows, had you tried Github's desktop client? I felt like it simplified things a bit for me.
If you've managed a pull request I think you may have had most of the hard parts already though. I recall without the desktop client the keys part was annoying...

Also, thanks for contributing!
I like how your function has simplified usage in terms of parameters compared to [Excel's implementation](https://support.office.com/en-us/article/TREND-function-e2f135f0-8827-4096-9873-9a7cf7b51ef1).
In the same way, you might even be able to have it work with just the `YList`, letting `NoOfIntervals` default to 0 or something. Unfortunately, M has not natively supported default parameter values, though you could achieve the same thing in a slightly more verbose way:
* marking the parameter with `optional`
* as a first statement to the function, assigning the default if applicable: `NoOfIntervals = if (NoOfIntervals=null) then 0 else NoOfIntervals,`

Anyway, I'll merge it either way. :)

**Comment by ImkeF** [comment]
Thanks!
Good tip re the optionals! But in this case I think it doesn't make sense to default to 0 because it wouldn't return anything then.
Had a closer look yesterday into GitHub and "spoke" with Ivan Bond and after that wasn't sure if sending a pull request was actually the right thing to do here. As he is just hosting a branch. 
I'm going to write a blogpost about creating (descriptive) statistical functions in M including the call out to the community to rebuild Excel's statistical functions (or more) in M. If this generates response - would you be happy to pull them all into your repository or shall I give my branch as the desired target instead? I would prefer to use your's directly but as I see now that this could generate some work... Let me know please :-)

**Comment by tycho01** [comment]
I'd be glad to merge any contributions, sure. Thanks for attending me to Ivan's branch; I hadn't quite noticed his additions so far as I hadn't received a pull request from him yet so far.
As to pull requests, for our own branches each of us can choose to merge in whichever of each other's commits as we like (assuming merge compatibility -- if not it'll start asking questions).
In that sense, even if you'd originally forked from mine, Ivan should also still be able to merge in and use your additions, and vice versa.
I imagine creating pull requests from your branch to his directly should also be possible, but I'm not sure how yet.
Most of his additions I don't mind merging in either, but presuming he'd be in favor as well, I should probably talk to him about his decision to move the hard-coded file path from `LoadPath.m` to `Load.m`. I'll mention you there so you'd get a notification on it as well.

**Comment by tycho01** [comment]
Update: discussion [here](https://github.com/tycho01/pquery/pull/9).

**Pull request merged**
